import { homedir } from 'node:os';
import { join } from 'node:path';
import { installFiles } from '../install/file-writer.js';
import { escapeJsonString, promptCaptureHookScript } from '../install/prompt-hook.js';
import type { CodexSkillPathMode, InstallFile, InstallOptions, InstallResult } from '../install/types.js';

export async function installCodex(options: InstallOptions = {}): Promise<InstallResult> {
  return installFiles('codex', codexFiles(options.homeDir ?? homedir(), options.codexSkillPathMode, options.includeHooks, options.autoSafePreferences), options);
}

export function codexFiles(homeDir = homedir(), mode: CodexSkillPathMode = 'auto', includeHooks = false, autoSafePreferences = false): InstallFile[] {
  const files = resolveCodexSkillPaths(homeDir, mode).map((target) => ({
    path: target.path,
    description: target.description,
    content: codexSkillContent()
  }));

  if (includeHooks) files.push(...codexHookFiles(homeDir, autoSafePreferences));
  return files;
}

function resolveCodexSkillPaths(homeDir: string, mode: CodexSkillPathMode): { path: string; description: string }[] {
  const agentsPath = join(homeDir, '.agents', 'skills', 'contextbook', 'SKILL.md');
  const codexPath = join(homeDir, '.codex', 'skills', 'contextbook', 'SKILL.md');

  if (mode === 'agents') return [legacyAgentsTarget(agentsPath)];
  if (mode === 'codex') return [canonicalCodexTarget(codexPath)];
  if (mode === 'both') return [canonicalCodexTarget(codexPath), legacyAgentsTarget(agentsPath)];

  return [canonicalCodexTarget(codexPath)];
}

function codexHookFiles(homeDir: string, autoSafePreferences: boolean): InstallFile[] {
  const scriptPath = join(homeDir, '.codex', 'hooks', 'contextbook-user-prompt-submit.js');
  const guidePath = join(homeDir, '.codex', 'hooks', 'contextbook-user-prompt-submit.md');
  return [
    {
      path: scriptPath,
      description: 'Codex UserPromptSubmit hook helper for deterministic Contextbook prompt signal capture and suggestion bridge',
      content: promptCaptureHookScript('codex', { autoSafePreferences })
    },
    {
      path: guidePath,
      description: 'Codex hook configuration snippet for enabling Contextbook prompt signal capture and suggestion bridge',
      content: codexHookGuide(scriptPath, autoSafePreferences)
    }
  ];
}

function canonicalCodexTarget(path: string): { path: string; description: string } {
  return {
    path,
    description: 'Codex user skill for Contextbook learning workflows (canonical Codex/OMX path)'
  };
}

function legacyAgentsTarget(path: string): { path: string; description: string } {
  return {
    path,
    description: 'Codex user skill for Contextbook learning workflows (historical ~/.agents compatibility path)'
  };
}

function codexHookGuide(scriptPath: string, autoSafePreferences: boolean): string {
  return `# Contextbook Codex UserPromptSubmit Hook

This file was generated by \`contextbook setup\`.

Contextbook does **not** edit your Codex hook config automatically. To enable prompt signal capture, merge this snippet into \`~/.codex/hooks.json\`:

\`\`\`json
{
  "hooks": {
    "UserPromptSubmit": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "node \\\"${escapeJsonString(scriptPath)}\\\"",
            "timeout": 30,
            "statusMessage": "Capturing Contextbook learning signal"
          }
        ]
      }
    ]
  }
}
\`\`\`

After changing Codex hooks, use \`/hooks\` in Codex to review and trust the hook definition.

Codex hook context injection can vary by installed Codex runtime. Treat this helper as best-effort until you verify the generated hook with \`/hooks\` and a live local prompt. If your Codex runtime does not inject hook stdout as model context, run \`contextbook memory context --json\` manually from the Contextbook skill.

## Safety

- The hook calls \`contextbook memory hook-suggest --source codex --mode ${autoSafePreferences ? 'auto-safe' : 'suggest'} --json\`.
- Contextbook classifies only explicit learning/preference signals.
- Contextbook does not persist or echo the raw prompt text.
- The hook may surface Contextbook memory for learning questions.
- ${autoSafePreferences ? 'Generated setup hooks may auto-apply only policy-approved low-risk style preferences through `contextbook memory apply-preference-signals --mode auto-safe`, with backup/audit/undo.' : 'Adapter hook installs stay suggestion-only unless you explicitly use `--auto`.'}
- Contextbook never auto-applies profile updates, weak-term updates, learner judgments, restore/repair/recover actions, or raw prompt storage from hooks.
- The hook exits successfully even if capture fails, so it should not block Codex.
`;
}

function codexSkillContent(): string {
  return `---
name: contextbook
description: Use when the user wants to learn concepts behind the code they just touched, generate project-grounded learning moments, or answer why a development/CS concept matters in this repository using the local contextbook CLI.
---

# Contextbook

Use the local \`contextbook\` CLI to turn this repository's code evidence into project-grounded learning notes.

## When to use

- The user asks what they can learn from the code they just changed.
- The user asks "why" a concept matters in the current project.
- The user wants interview-ready wording for concepts found in their code.

## Workflow

1. Prefer deterministic local evidence over generic explanation.
2. If project memory may be stale, run:
   \`\`\`bash
   contextbook scan
   \`\`\`
3. For the default one-shot AI context bundle, run:
   \`\`\`bash
   contextbook memory context --json
   \`\`\`
4. Use the lower-level memory contracts only when debugging a specific layer:
   \`\`\`bash
   contextbook project --json
   contextbook learner --json
   contextbook memory signals --json
   contextbook memory suggest-weak-terms --json
   contextbook memory suggest-profile-updates --json
   \`\`\`
5. To record explicit user feedback as append-only Learner Memory, run \`contextbook memory add-signal --type <allowed-type> --concept "<concept>"\` only when the user clearly expresses feedback. For hook-ready prompt feedback capture, use \`contextbook memory capture-prompt --prompt "<user prompt>" --source codex --json\`; it stores sanitized signal notes, not raw transcript text. For hook suggestion context, use \`contextbook memory hook-suggest --prompt "<user prompt>" --source codex --json\`; it emits hook-safe/read-only memory context; generated setup hooks may apply only low-risk auto-safe preferences. Do not infer ability or mutate profile.
6. Profile update candidates are preview-first. Use \`contextbook memory apply-profile-update --candidate <id|index> --dry-run\` to show the exact preferences-only change, and run without \`--dry-run\` only after explicit user approval.
7. Explicit prompt preferences are also preview-first. Use \`contextbook memory apply-preference-signals --prompt "<user prompt>" --source codex --mode auto-safe --dry-run\` to preview allowlisted language/order/length/command-volume updates without storing the raw prompt.
8. For learning moments, run:
   \`\`\`bash
   contextbook learn
   \`\`\`
8. For concept questions, run:
   \`\`\`bash
   contextbook why "<question>"
   \`\`\`
9. Preserve Contextbook's evidence level: \`direct\`, \`related\`, or \`general\`.
10. Do not claim stronger project evidence than the CLI output provides.
11. Do not ask for API keys; Contextbook v0.1 is local and deterministic-first.

## Useful commands

- \`contextbook init\` — create project and learner memory files.
- \`contextbook scan\` — refresh local project evidence.
- \`contextbook memory context --json\` — inspect Project/Learner/Conversation Memory in one stable AI-readable bundle.
- \`contextbook project --json\` — inspect Project Memory in a stable AI-readable shape.
- \`contextbook learner --json\` — inspect Learner Memory in a stable AI-readable shape.
- \`contextbook memory signals --json\` — inspect recent explicit memory signals.
- \`contextbook memory suggest-weak-terms --json\` — inspect suggestion-only weak-term review candidates without mutating learner memory.
- \`contextbook memory suggest-profile-updates --json\` — inspect suggestion-only profile update candidates without editing profile/preferences.
- \`contextbook memory apply-profile-update --candidate <id|index> --dry-run\` — preview an explicit preferences-only profile candidate before any write.
- \`contextbook memory apply-preference-signals --prompt "한국어로 쉽게 설명해줘" --source codex --mode auto-safe --dry-run\` — preview allowlisted preference writes from an explicit prompt with reversible auto-safe policy.
- \`contextbook memory add-signal --type feedback.confused --concept "event loop"\` — record explicit feedback only.
- \`contextbook memory capture-prompt --prompt "뭔소리야 너무 추상적임" --source codex --json\` — deterministically capture explicit prompt feedback without storing the raw prompt.
- \`contextbook memory hook-suggest --prompt "앞으로 한국어로 짧게 설명해줘" --source codex --json\` — produce hook-safe suggestion context with setup-managed auto-safe preference policy.
- \`contextbook learn\` — produce 1-3 learning moments.
- \`contextbook why "cleanup 왜 해야 돼?"\` — answer with project context, plain language, developer term, CS link, interview sentence, and evidence files.
- \`contextbook profile\` — inspect the learner profile.
`;
}
